### ISSUE TITLE
Track interactions through all Search Access Points

### ISSUE THREAD

**Issue by past** [cliqz-oss/browser-core#10]
Cliqz essentially unifies all SAPs into one (the URL bar) when installed, by using the freshTab for about:home and about:newtab and hiding the search bar. Also, clicking on the freshTab's search box actually focuses the URL bar where the user interaction continues. This simplifies things a lot.

It would be great however to track the times a user initiated their interaction on the freshTab's search box, compared to the amount of times they searched directly from the awesomebar. One additional probe in freshTab seems sufficient since we could presumably subtract that count from the awesomebar search count, but if you folks feel it would be best to add both probes that's fine.

Should this be part of Cliqz telemetry or part of Test Pilot telemetry? If you'd prefer the latter and can point me to where the probe should be added, I will take care of it.

**Comment by dominiks-cliqz** [comment]
Hi @past, tracking the SAP is already possible with our current telemetry signals—no need to add anything :)! We can distinguish between searches originating in the awesomebar, on cliqztab, and from the context menu. 

FYI: @luciancor

**Comment by past** [comment]
Oh, that is great to hear, thanks!
