### ISSUE TITLE
Latest Nightly broke the panel again

### ISSUE THREAD

**Issue by past** [cliqz-oss/browser-core#24]
I haven't had time to find out which changeset broke it, but [bug 1321556](https://bugzilla.mozilla.org/show_bug.cgi?id=1321556) is one candidate. (CC @mak77)

**Comment by mak77** [comment]
I don't think it's that bug, it barely removes a couple bindings that are mostly unused and not related to the urlbar at all.
I wonder if the proper fix for https://bugzilla.mozilla.org/show_bug.cgi?id=1323600 broke the workaround (that now should not be needed anymore)?

**Comment by past** [comment]
I think you are right! I made the change locally and it seems to work.

**Comment by mak77** [comment]
The fix landed in both Nightly and Aurora, so I think the workaround can be safely removed if that's enough.

**Comment by luciancor** [comment]
@past @mak77 
Simply removing the workaround could still cause some troubles for some users.
What do you guys think about keeping it for a short while more?
Here is a PR for it - https://github.com/cliqz-oss/browser-core/pull/25

**Comment by mak77** [comment]
Which users? the ones in Aurora and Nightly who didn't get an update yet? I honestly think it's an ignorable percentage, considered those channels get daily updates.
But surely there's no downside in keeping it apart from some additional code logic.

**Comment by past** [comment]
That's fine by me.

**Comment by past** [comment]
Fixed by #25.
