### ISSUE TITLE
Use the proper extension ID for setting the install date

### ISSUE THREAD

**Issue by luciancor** [cliqz-oss/browser-core#28]
1482421759636	addons.manager	WARN	Exception calling callback: TypeError: arguments[0] is null (chrome://cliqzmodules/content/Extension.jsm:158:17) JS Stack trace: Extension.setInstallDatePref/<@Extension.jsm:158:17 < safeCall@AddonManager.jsm:188:5 < makeSafe/<@AddonManager.jsm:204:25 < Handler.prototype.process@Promise-backend.js:937:23 < this.PromiseWalker.walkerLoop@Promise-backend.js:816:7 < this.PromiseWalker.scheduleWalkerLoop/<@Promise-backend.js:750:11

**Comment by past** [comment]
Oh, this just needs to pass aData.id to Extension.init(), just like we do it for FirefoxTelemetry.init() in startup(). Is anyone working on this or do you want me to whip up a patch?

**Comment by luciancor** [comment]
@past we will take care of it, no worries :) Will provide a PR for it soon

**Comment by past** [comment]
Fixed by #30.
