### ISSUE TITLE
The em:description fiels in install.rdf is empty

### ISSUE THREAD

**Issue by past** [cliqz-oss/browser-core#33]
I think this is the case in the AMO version as well, but the Addons Manager looks empty without it. Ideally this would contain something like:

Get search results faster, directly in the browser. Start typing and see suggestions from around the Web in real time, right below the URL bar. And because Cliqz avoids collecting personally identifiable data, or building user profiles, your results are more private.

Learn more about this Test Pilot experiment at https://testpilot.firefox.com/.

**Comment by luciancor** [comment]
For the AMO version we keep it empty because it gets fetched from the AMO store. It is more flexible to change it from there. Not sure if this is also valid for other signing methods (eg: unlisted addon)

**Comment by past** [comment]
I'm not sure, @clouserw what do you think?

**Comment by past** [comment]
I was told by AMO folks that unlisted add-ons are not treated differently in that regard, so no code changes should be necessary. I guess you can confirm this after you submit the unlisted add-on and try to install it locally.

**Comment by past** [comment]
I got another feedback that unlisted add-ons should fetch any info from AMO in the about:addons page and if that happens, it's a bug. I guess we need to test and if it works for now use it, until 5.12 where we should add a description field.

**Comment by luciancor** [comment]
I tested a bit earlier by creating a new submission but I do not get the description. Not sure if I need to wait more due to some caching policies or something like that.

Here is a sample XPI https://www.dropbox.com/s/70z7hhahb9jqnyp/description_test-0.0.1-fx.xpi?dl=0

And I guess the call is https://services.addons.mozilla.org/en-US/firefox/api/1.5/search/guid:description_test%40cliqz.com?src=firefox&appOS=Darwin&appVersion=51.0

but nothing is returned

**Comment by past** [comment]
Yeah, that matches the last comment from AMO engineers. If you can add a description field to install.rdf and package it that would be great, otherwise we'll ship what we have so far and fix this in 5.12.

**Comment by luciancor** [comment]
Sure - will try to get the text from our PR colleagues and send you an updated Pull Request and build

**Comment by past** [comment]
@luciancor we could just use the long description that was agreed for the test pilot page:

> Get search results faster, directly in the browser. Start typing and see suggestions from around the Web in real time, right below the URL bar. And because Cliqz avoids collecting personally identifiable data, or building user profiles, your results are more private.

**Comment by past** [comment]
Closed by #34.
