### ISSUE TITLE
Startpage address is invalid

### ISSUE THREAD

**Issue by topaxi** [cliqz-oss/browser-core#38]
I activated cliqz using Testpilot on my workstation at home and have setup Firefox Sync. On my Notebook I now get `about:cliqz` and a bit error message with "The address isn't valid", and for some reason, the cliqz test-pilot only shows up on my workstation at home, not on my notebook. This means I'm effectively unable to disable the test-pilot on my notebook.

As a side-effect, every time I start Firefox on my notebook, it throws away my previous session and I'm unable to restore it.

**Comment by stefanie-cliqz** [comment]
Hi @topaxi, we will try to reproduce the issue you describe. To clarify: you have Test Pilot (including Cliqz) installed on your work station, but on your notebook you use Firefox without Test Pilot (and without Cliqz). Is that correct?

Does about:cliqz appear only on the start page or on every new tab? On your notebook, please go to about:addons and check if Cliqz is listed among your installed add-ons. Also, if you go to about:preferences, is about:cliqz saved as your start page?

Thanks!

**Comment by topaxi** [comment]
I have test-pilot activated on both computers. But cliqz does not show up as an test-pilot experiment on my notebook. (I guess this might have something to do with localization and my internet provider at home and work are different? Even though both are located in Bern, Switzerland).

`about:cliqz` only appears on new windows (not tabs). Indeed `about:cliqz` was configured as my start page, I guess this was due to Firefox Sync. Preferably this shouldn't get synced (if possible). If this is something that depends on Firefox or Firefox Sync and not cliqz, this issue can be closed.

**Comment by stefanie-cliqz** [comment]
Thanks for clarifying. We were able to reproduce. Seems to be an issue with Firefox sync. We'll investigate further and will work with Firefox to fix this. Hope this doesn't stop you from giving the Cliqz add-on a try. All the best!

**Comment by luciancor** [comment]
Thanks @topaxi for your feedback! 

During our investigation we found out that the Sync functionality synchronizes only [add-ons which you install directly from the AMO store](https://support.mozilla.org/en-US/kb/sync-your-add-ons-another-copy-firefox#w_which-add-ons-will-be-synced). Our test pilot experiment was installed via the Test Pilot extension therefore it will not be synced on both your machines. 
We will share our findings with Firefox for a better experience in the future.

We can definitely suggest you to install the official version from [here](https://addons.mozilla.org/en-US/firefox/addon/cliqz/) This one should fix both this issue and https://github.com/cliqz-oss/browser-core/issues/37 .

**Comment by Tobias-B-Besemer** [comment]
I still get "The address isn’t valid" by "about:cliqz" with Cliqz installed from AMO.
I'm using FF56.0a1, 64-bit with E10s.

**Comment by luciancor** [comment]
@Tobias-B-Besemer thanks for your report! We have an incompatibility with latest version of Firefox. 
For Firefox Beta (55) we already have a fix and we wait for the AMO review. You can see this fix on our AMO beta - https://addons.mozilla.org/firefox/downloads/file/671842/cliqz_search_directly_in_your_browser-2.16.2.1b0-fx.xpi?src=devhub

For Firefox Nightly (56) we are still investigation

**Comment by Tobias-B-Besemer** [comment]
"about:cliqz" seems to work with the beta with FF56.0a1! :-)

**Comment by Tobias-B-Besemer** [comment]
What's about using "Activity Stream" and "Cliqz" together?
Is there an issue for it?

**Comment by Tobias-B-Besemer** [comment]
Tested the beta... Makes FF56.0a1 really slow on my older machine... :-/

**Comment by luciancor** [comment]
"about:cliqz" is fine on FF56 but there is an issue with search there - this is what we are investigation now :) on top we will also look into the performance issue you mentioned, thanks for the report! 

both "Activity Stream" and "Cliqz" change the new tab page - we consider that an incompatibility
