### ISSUE TITLE
ALT+Enter doesnt work

### ISSUE THREAD

**Issue by kawinga** [cliqz-oss/browser-core#39]
Hi,

i can not open a new tab from within the Adress-Bar wiht ALT+Enter.

If you need any further information, please inform me.

Kind regards,

Robert

> Name: Firefox
> Version: 50.1.0
> Build-ID: 20161208153507
> Update-Kanal: release
> User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0
> Betriebssystem: Windows_NT 6.1
> Fenster mit mehreren Prozessen: 1/1 (aktiviert durch Benutzer)
> Abgesicherter Modus: false

**Comment by luciancor** [comment]
hey @kawinga!,

Sorry for the slow reply! 
This issue should have been fixed long ago - can you please confirm if everything is fine on your end?

Cheers
