### ISSUE TITLE
Cliqz replaces Firefox settings, risk to lose the current session

### ISSUE THREAD

**Issue by KitsuneRal** [cliqz-oss/browser-core#45]
I am a Test Pilot user and tried to use Cliqz recently. Here's my primary feedback: please be very clear that your extension resets "When Firefox starts" to "Open the home page" with the home page set to "about:cliqz". With that you've just successfully dropped my current session with tens of tabs, just because I wanted to restart a computer and didn't notice you've changed the setting. So far I'm switching the whole thing off because I can't trust you. I might be trying to protect my data, but somehow you feel free to overwrite some of them (the browser settings), and it's not an under-the-hood setting in about:config. What else have you overwritten?

**Comment by Tobias-B-Besemer** [comment]
Sounds for me like Issue #37.

**Comment by luciancor** [comment]
@KitsuneRal thanks for your feedback and sorry for the slow reply! Somehow these issue went unobserved but we will be much more careful about this in the future!

For your concrete problem - we are indeed overriding the start page when you install our addon, this is described in our "About this extension" section on AMO - https://addons.mozilla.org/en-US/firefox/addon/cliqz/ 
I can highly recommend you to give another try! 
Please let us know if we can support you somehow.

Cheers!
