### ISSUE TITLE
Do you tell to trackers how not to track?

### ISSUE THREAD

**Issue by piotr-yuxuan** [cliqz-oss/browser-core#48]
Hi! Thanks for your browser, it's a great idea towards a better Web.

As Cliqz comes as various technical solutions (browser plugin, mobile and desktop browsers), have you thought about a way for Cliqz to consistently signal itself to trackers? So they could just don't even try to track Cliqz users — perhaps you do use DNT header field?

If such information is already provided in your documentation, sorry for that I didn't stumble across it; would you mind make it more obvious to find? :-)

**Comment by piotr-yuxuan** [comment]
In case some might find it useful, some anti-tracking values are stored [here](https://github.com/cliqz-oss/browser-core/blob/1b5ce54fbff4bf1a78abb16e20ebdab5ba4cae8e/modules/antitracking/sources/config.es#L10-L19):
``` es6
export const DEFAULTS = {
  safekeyValuesThreshold: 4,
  shortTokenLength: 6,
  placeHolder: 'cliqz.com/tracking',
  cliqzHeader: 'CLIQZ-AntiTracking' /* http header sent when a tracker is blocked */,
  enabled: true,
  cookieEnabled: true,
  qsEnabled: true,
  bloomFilterEnabled: true,
};
```

Once more, warm thanks for the very useful work you done with Cliqz.

**Comment by piotr-yuxuan** [comment]
no response

**Comment by sammacbeth** [comment]
Hi @piotr-yuxuan. Sorry for not responding previously, these issues were not being watched.

To answer your question, we do not proactively signal our presence to trackers. If we take an action against a tracker we do set a HTTP header: `CLIQZ-AntiTracking`. On Ghostery this header is `Ghostery`. This means that trackers can filter anonymised Cliqz traffic.

Another possibility would be to use something like `DNT`, however it is considered bad practice to set this to be on by default [as per the spec](https://www.w3.org/TR/tracking-dnt/#privacy.not-preconfigured). This setting should be configured by the user, and this setting is present in the Cliqz browser.
