### ISSUE TITLE
Record the telemetry session ID along with Cliqz telemetry data

### ISSUE THREAD

**Issue by past** [cliqz-oss/browser-core#5]
In order to properly associate TP telemetry with Cliqz telemetry data the Firefox session and subsession IDs need to be sent along with the main Cliqz telemetry ping. Here is some example code for retrieving them:

```
Cu.import("resource://gre/modules/TelemetryController.jsm", this);
let p = TelemetryController.getCurrentPingData();
... = p.payload.info.sessionId
... = p.payload.info.subsessionId
```

There is still some discussion in an email thread about whether this is absolutely necessary, but I'm filing this issue to track the work if we end up doing it.

**Comment by luciancor** [comment]
@past is there any update for this one? Should we prepare a PR?

**Comment by luciancor** [comment]
No issues from our side - will prepare a PR and send it over. I was not sure about the outcome of the email thread :)

**Comment by past** [comment]
Me neither :) I wonder if we should get Dominik and Dave to confirm that we want to fix this.

**Comment by luciancor** [comment]
As it is an easy fix I created a PR for it in case we need it. Maybe @dominiks-cliqz can give us his input.

**Comment by past** [comment]
Turns out that we don't need this after all, so I'll close this issue. Thanks for working with me on this!
