### ISSUE TITLE
Firefox Context menu behaves strangely after installing addon (Cliqz.8.19.5.v2.xpi)

### ISSUE THREAD

**Issue by pauljt** [cliqz-oss/browser-core#51]
Testing this add-on (Cliqz.8.19.5.v2.xpi) in Firefox Nightly (OSX, Build 20170927100120) causes weird context menu (right-click) behavior after I install the add-on. The content menu floats above all other windows, and click outside the menu doesn't dismiss it as it should (the only way to dismiss it is by choosing an option from the menu). I was advised to file a bug here, let me know if you need further details.

**Comment by kateryna-cliqz** [comment]
Hi Paul. Thanks for your feedback. We have an issue with Context Menu in Firefox Nightly 57 and later versions. We are planning to fix it in next iteration. For now Cliqz.8.19.5.v2 should work with Firefox Nightly 56. 
Can you please try with the latest Firefox 56 beta you have and check if the issue reproducible there?
Thanks again. And please feel free to share with us any findings you will experience. 
Best, Kate
