### ISSUE TITLE
Cliqz survey pages need to be updated with the new Test Pilot Photon design

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [cliqz-oss/browser-core#55]
**[Affected versions]:**
- Firefox 57.0.4 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Test Pilot was already installed on a new profile.

**[Steps to reproduce]:**
1. Open Firefox browser with the profile from prerequisites and navigate to https://testpilot.firefox.com/experiments/cliqz page.
2. Click the "Enable Cliqz" top right page button.
3. Dismiss the displayed tour modal and click the "Give Feedback" button.
4. Observe the design of the survey page opened in a new tab.

**[Expected result]:**
- The survey page follows the new test Pilot Photon design and contains the dark blue background and the new Firefox logo on top. 

**[Actual result]:**
- The survey page still has the old background and Firefox logo.

**[Notes]:**
- This issue also occurs for the Cliqz disabled experiment survey. 

### Enabled experiment survey ###
![enabled_survey](https://user-images.githubusercontent.com/17258026/34726987-382f6a00-f55e-11e7-824c-5ac16e55fa15.png)

### Disabled experiment survey ###
![disabled_survey](https://user-images.githubusercontent.com/17258026/34727008-4a38bb3e-f55e-11e7-87e0-fe33e389b6dd.png)

### New test Pilot Photon design for survey pages ###
![new_survey_design](https://user-images.githubusercontent.com/17258026/34727037-60ffbf5c-f55e-11e7-9c30-ff8a3a062222.png)

**Comment by luciancor** [comment]
Closing this as Cliqz Test Pilot experiment was retired
