### ISSUE TITLE
Create a metrics.md

### ISSUE THREAD

**Issue by past** [cliqz-oss/browser-core#6]
We need a document that contains more detailed information about the data we are collecting that the test pilot page will link to. Here is an [example](https://github.com/mozilla/universal-search/blob/master/docs/metrics.md) from another Test Pilot experiment. Javaun is already working on this.

**Comment by dominiks-cliqz** [comment]
@past I talked with David two weeks back and we compiled a list of metrics we are interested in:

https://docs.google.com/spreadsheets/d/1kCmt4F_pWuJ5lFoXra8tr9j7iDC46GQUrdrGyMlymZw/edit?ts=58408ca8#gid=0.

Would this kind of information be sufficient?

**Comment by past** [comment]
@dominiks-cliqz I think we have all the information we need, it's just a matter of compiling the document. I believe the plan is to add the new metrics in this document and link to other documents describing the parts that belong to already existing data collection, like Firefox Telemetry and Cliqz Telemetry.

**Comment by past** [comment]
Fixed by #26.
