### ISSUE TITLE
what is the purpose of the hpnv2? 

### ISSUE THREAD

**Issue by pventuzelo** [cliqz-oss/browser-core#67]
Hi, 

I was looking at the source code and the module hpnv2 use WebAssembly.
What is exactly the purpose of this module?

Thanks

**Comment by acatarineu** [comment]
Hi,

hpnv2 module is the client-side implementation of this paper: https://arxiv.org/pdf/1812.07927.pdf

The idea is to be able to have a certain degree of rate-limiting protection without compromising users anonymity. Basically, make it difficult for attackers to abuse anonymity and send fake data to disrupt our services. The kind of data we collect, and why, can be found here: https://gist.github.com/solso/423a1104a9e3c1e3b8d7c9ca14e885e5 (although that belongs to a different module, human-web).

The WebAssembly module is for the cryptographic operations, which are a bit expensive. It's open-source and can be found here: https://github.com/cliqz-oss/anonymous-credentials.

Feel free to ask if you have further questions about that topic.
