### ISSUE TITLE
Install cliqz as "search tool" (not addon) in firefox

### ISSUE THREAD

**Issue by eauchat** [cliqz-oss/browser-core#70]
I'm not sure this is the right place to ask this, so please redirect me to the right one if it isn't.

Discovering cliqz I was very interested in the work you're trying to do.
Wanting to use cliqz as default search engine in firefox, I just found the "cliqz tab" add on.
I couldn't find a way to add cliqz simply as "search tool" in the menubar (did I miss something?). I know this wouldn't enable all the functionalities that you try to provide (like searching automatically while typing...).  
But let's say I don't want to install one more addon and already have a customized new tab page, also I'm happy with my browser the way it is. Is there a way to search directly with cliqz from the firefox search bar, like most search engine provide?

Thank you for your attention and the work you do :-)

**Comment by ecnmst** [comment]
Hi @eauchat - thanks for the nice words. It is very encouraging to us. 

One way to get [https://beta.cliqz.com/](https://beta.cliqz.com/) as default in Firefox would be to do the following: 

1. Visit [https://beta.cliqz.com/](https://beta.cliqz.com/)
2. Click on the settings icon in the top right corner and you should see this:
![step1](https://user-images.githubusercontent.com/7120632/72448806-f5c39580-37b7-11ea-896f-b3ff3fecdead.png)
3. Click on `Add Cliqz as Search Provider`. This will trigger a dialog box from Firefox, asking you to confirm. 
![step2](https://user-images.githubusercontent.com/7120632/72448879-15f35480-37b8-11ea-90c7-8d1d5ebda1e8.png)
4. IMPORTANT: Do not forget to tick the box `Make this the current search engine`.
5. Click `Add` and you should be set. Query suggestions in the Firefox dropdown should be powered by Cliqz and searching should take you to [https://beta.cliqz.com/](https://beta.cliqz.com/)

Let me know if it works out.

**Comment by eauchat** [comment]
Hey @ecnmst,

Thank you for your super swift and detailed reply.
The solution you proposed worked for me.

I'm not used to adding search engines this way, so I didn't think of that option and also I didn't stumble upon it because the button was not shown at first in my browser, because of a user agent issue (error not from cliqz but from me). It would be nice, when you find time for that, to make it available directly from the Firefox settings as well (but maybe you already planned on doing it).

Thanks again for your great work. And a special note for the little tracker icon, it's a really great tool to know what to expect before having to click on a website.
