### ISSUE TITLE
dat protocol support in cliqz browser

### ISSUE THREAD

**Issue by eauchat** [cliqz-oss/browser-core#72]
In his (very nice :)) presentation at FOSDEM2020 @sammacbeth talked about how dat protocol [is now supported in cliqz browser beta on windows mac and linux](https://sammacbeth-fosdem.hashbase.io/#/6).
I installed cliqz browser from the cliqz debian-release repository [as specified in instructions here](https://cliqz.com/en/desktop/cliqz-for-linux), but when I go to a dat url (lets say: `dat://sammacbeth-fosdem.hashbase.io/`) it doesn't work (= it just searches that string in cliqz search engine).

I imagine that the version I installed is an older version that didn't have dat implemented, but I didn't manage to find the "beta" version mentioned in the presentation. There seem to be [nightly versions here](https://cliqz.com/en/latest), but apparently not for linux.  
I also tried to install the addon specified on that same page, but it doesn't seem to make a difference on the dat support.

Is there a place, or instructions somewhere on how to install cliqz browser beta (or some cliqz browser version with dat support)?

Thanks a lot for your attention and all the great work you do.

**Comment by sammacbeth** [comment]
dat support will land in the next release, but if you can't wait that long it can be tested in our nightly builds at https://cliqz.com/en/latest. Note these are unstable builds primarily for internal testing.

**Comment by eauchat** [comment]
Thank you @sammacbeth for your answer. As I was mentioning in my question the page https://cliqz.com/en/latest seem to contain only packages for windows and mac, but in your slides you mentioned that linux was also supported, that's why I was asking here.

**Comment by sammacbeth** [comment]
Sorry, I miss-read your original post. You can grab a recent linux beta build from here: https://repository.cliqz.com/?prefix=dist/beta/1.32.1/20200206222711/

**Comment by eauchat** [comment]
I didn't manage to get something from the link you sent, the page just says `Error: [object Object]`.  
I was just thinking maybe there would be a nightly repository I could install cliqz from, or somewhere with latest builds.  
Maybe I'll just wait for the next release with dat support, which hopefully will come soon.  
Thanks anyway.

**Comment by sammacbeth** [comment]
This is now available in all release channels. You can enable dat support in preferences under the "Labs" section (`about:preferences#experiments`).

**Comment by eauchat** [comment]
Thanks for your answer @sammacbeth, I indeed could now update cliqz and use the dat support, it works great!. Thank you for the great work :)
