### ISSUE TITLE
Please make changelogs more detailed.

### ISSUE THREAD

**Issue by Rtizer-9** [cliqz-oss/browser-core#73]
Can you please make your changelogs more detailed for ghostery, ghostery-start-tab and cliqz.

What's really the difference between ghostery start tab and cliqz-tab?

One last thing: please make the broken-page reporting less cumbersome, look the implementation of I don't care about cookies.

**Comment by sammacbeth** [comment]
Hi thanks for your report and your interest in our code. We discussed this internally and have some plans to improve external communication of our changelogs. As of the next release we plan publish a changelog file in the source tree. Hope that helps!
