### ISSUE TITLE
Is there someone still interested in supporting this project?

### ISSUE THREAD

**Issue by smhillin** [cliqz-oss/browser-core#78]
Hello, 

We are interested in reviving this project and wanted to talking with anyone why maybe able provide some insight, guidance, or even consulting on the project.  If thats possible please reach out to me at shaun@natvz.io

thanks!

Shaun

**Comment by sammacbeth** [comment]
Hi Shaun,

This project will no longer be maintained by Cliqz. The subset of modules used for Ghostery products have been extracted to the https://github.com/ghostery/common repo, which will be maintained. For guidance, either @chrmod or myself may be able to help - perhaps if you share more about what you want to do with the project we can better direct you.

Thanks,
Sam.

**Comment by chrmod** [comment]
@smhillin we're always happy to talk. I've sent you an email.
